import argparse
import re
import sys
from dataclasses import dataclass
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))
from inline_grammar import parse_peg_grammar
from grammar_types import load_grammar_types, load_matcher_rule_overrides
from transformer_plan import (
    ChoiceNode,
    ExtractionKind,
    LiteralNode,
    ReferenceNode,
    SequenceNode,
    classify_choice_alternatives,
    classify_sequence_elements,
    is_pure_reference_choice,
    literal_string_values,
    plan_extraction,
    rule_to_ast,
    sequence_skip_reason,
    _is_by_value,
)


# ---------------------------------------------------------------------------
# Rule overrides - mirrors AddRuleOverride() calls in matcher.cpp.
# These rules are replaced with special matchers that produce IdentifierParseResult
# (or similar) directly, bypassing the generic ListParseResult path.
# When one of these appears as an alternative in a choice rule the generated
# Internal must check ParseResultType rather than calling transformer.Transform<>.
# ---------------------------------------------------------------------------

scripts_dir = Path(__file__).parent.parent
src_dir = scripts_dir.parent / 'src'
peg_dir = src_dir / 'parser' / 'peg'
statements_dir = peg_dir / 'grammar' / 'statements'
type_dir = scripts_dir / 'parser'
transformer_dir = peg_dir / 'transformer'
include_peg_dir = src_dir / 'include' / 'duckdb' / 'parser' / 'peg' / 'transformer'
matcher_cpp_path = peg_dir / 'matcher.cpp'

GENERATED_HEADER = "// AUTO-GENERATED by scripts/parser/generate_transformer.py -- DO NOT EDIT\n"


def load_identifier_override_rules(grammar_types_file):
    """Return matcher overrides that produce IdentifierParseResult."""
    matcher_overrides = load_matcher_rule_overrides(grammar_types_file)
    return {
        rule_name
        for rule_name, info in matcher_overrides.items()
        if isinstance(info, dict) and info.get("matcher") in ("identifier", "reserved_identifier")
    }


def manual_body_exists(gram_stem, rule_name):
    pattern = re.compile(rf'\bPEGTransformerFactory::Transform{re.escape(rule_name)}\s*\(')
    preferred_path = transformer_dir / f"transform_{gram_stem}.cpp"
    paths = [preferred_path] if preferred_path.exists() else []
    paths.extend(path for path in transformer_dir.glob("transform_*.cpp") if path != preferred_path)
    return any(pattern.search(path.read_text()) for path in paths)


def generate_internal_declaration(rule_name):
    return (
        f"\tstatic unique_ptr<TransformResultValue> Transform{rule_name}Internal"
        f"(PEGTransformer &transformer, ParseResult &parse_result);\n"
    )


def generate_registration(rule_name):
    return f'\t{{"{rule_name}", &PEGTransformerFactory::Transform{rule_name}Internal}},\n'


def _box_result(return_type, return_by_value):
    """
    Generate the boxing return statement for an Internal function.
    Use std::move only for move-only types (unique_ptr<T>, vector<unique_ptr<T>>).
    Trivially-copyable types (enums, primitives) and copyable structs use a plain copy to
    avoid the performance-move-const-arg clang-tidy warning.
    """
    arg = "std::move(result)" if return_by_value else "result"
    return f"\treturn make_uniq<TypedTransformResult<{return_type}>>({arg});\n"


def _emit_string_result_extraction(var_name, source_expr, result_type="string"):
    # Extract a terminal value from a choice over matcher identifiers / keywords / string literals.
    # When the rule itself is an Identifier, the keyword/string-literal alternatives are wrapped so
    # the result is produced as an Identifier directly (no lossy string round-trip).
    def as_result(expr):
        return f"Identifier({expr})" if result_type == "Identifier" else expr

    identifier_value = f"{source_expr}.Cast<IdentifierParseResult>().identifier"
    if result_type != "Identifier":
        identifier_value = f"{identifier_value}.GetIdentifierName()"
    return (
        f"\t{result_type} {var_name};\n"
        f"\tif ({source_expr}.type == ParseResultType::IDENTIFIER) {{\n"
        f"\t\t{var_name} = {identifier_value};\n"
        f"\t}} else if ({source_expr}.type == ParseResultType::KEYWORD) {{\n"
        f"\t\t{var_name} = {as_result(f'{source_expr}.Cast<KeywordParseResult>().keyword')};\n"
        f"\t}} else if ({source_expr}.type == ParseResultType::STRING) {{\n"
        f"\t\t{var_name} = {as_result(f'{source_expr}.Cast<StringLiteralParseResult>().result')};\n"
        f"\t}} else {{\n"
        f"\t\t{var_name} = transformer.Transform<{result_type}>({source_expr});\n"
        f"\t}}\n"
    )


def generate_choice_internal_full(rule_name, return_type, return_by_value):
    """
    Fully auto-generated Internal for a pure-transformer choice rule.
    Static class member matching transform_function_t for the static TransformRule table.
    """
    return (
        f"unique_ptr<TransformResultValue> PEGTransformerFactory::Transform{rule_name}Internal(\n"
        f"    PEGTransformer &transformer, ParseResult &parse_result) {{\n"
        f"\tauto &list_pr = parse_result.Cast<ListParseResult>();\n"
        f"\tauto &choice_pr = list_pr.Child<ChoiceParseResult>(0);\n"
        f"\tauto result = transformer.Transform<{return_type}>(choice_pr.GetResult());\n"
        + _box_result(return_type, return_by_value)
        + f"}}\n"
    )


def generate_string_terminal_choice_internal(rule_name, return_type, return_by_value):
    """
    Choice wrapper for string-valued alternatives that can include matcher-provided
    terminal parse results, such as Identifier or ReservedIdentifier.
    """
    return (
        f"unique_ptr<TransformResultValue> PEGTransformerFactory::Transform{rule_name}Internal(\n"
        f"    PEGTransformer &transformer, ParseResult &parse_result) {{\n"
        f"\tauto &list_pr = parse_result.Cast<ListParseResult>();\n"
        f"\tauto &choice_pr = list_pr.Child<ChoiceParseResult>(0);\n"
        + _emit_string_result_extraction("result", "choice_pr.GetResult()", return_type)
        + _box_result(return_type, return_by_value)
        + f"}}\n"
    )


def _quote_cpp_string(value):
    return '"' + value.replace('\\', '\\\\').replace('"', '\\"') + '"'


def generate_literal_string_internal(rule_name, literals, return_by_value):
    """Fully auto-generated Internal for a string rule that consists only of literal tokens."""
    if len(literals) == 1:
        result_expr = _quote_cpp_string(literals[0])
        body = f"\tstring result = {result_expr};\n"
    else:
        body = (
            f"\tauto &list_pr = parse_result.Cast<ListParseResult>();\n"
            f"\tauto &choice_pr = list_pr.Child<ChoiceParseResult>(0);\n"
            f"\tauto result = choice_pr.GetResult().Cast<KeywordParseResult>().keyword;\n"
        )
    return (
        f"unique_ptr<TransformResultValue> PEGTransformerFactory::Transform{rule_name}Internal(\n"
        f"    PEGTransformer &transformer, ParseResult &parse_result) {{\n"
        + body
        + _box_result("string", return_by_value)
        + f"}}\n"
    )


def generate_choice_internal_with_default_alternatives(rule_name, return_type, return_by_value, excluded_alts):
    """Choice wrapper where syntax-only alternatives map to a default-constructed result."""
    excluded_conditions = " || ".join([f'choice_result.name == "{alt}"' for alt in excluded_alts])
    return (
        f"unique_ptr<TransformResultValue> PEGTransformerFactory::Transform{rule_name}Internal(\n"
        f"    PEGTransformer &transformer, ParseResult &parse_result) {{\n"
        f"\tauto &list_pr = parse_result.Cast<ListParseResult>();\n"
        f"\tauto &choice_pr = list_pr.Child<ChoiceParseResult>(0);\n"
        f"\tauto &choice_result = choice_pr.GetResult();\n"
        f"\t{return_type} result {{}};\n"
        f"\tif (!({excluded_conditions})) {{\n"
        f"\t\tresult = transformer.Transform<{return_type}>(choice_result);\n"
        f"\t}}\n" + _box_result(return_type, return_by_value) + f"}}\n"
    )


def generate_choice_internal_with_body(rule_name, return_type, return_by_value):
    """
    Internal for a choice rule that has identifier-override alternatives.
    Static class member matching transform_function_t for the static TransformRule table.
    """
    return (
        f"unique_ptr<TransformResultValue> PEGTransformerFactory::Transform{rule_name}Internal(\n"
        f"    PEGTransformer &transformer, ParseResult &parse_result) {{\n"
        f"\tauto &list_pr = parse_result.Cast<ListParseResult>();\n"
        f"\tauto &choice_pr = list_pr.Child<ChoiceParseResult>(0);\n"
        f"\tauto result = Transform{rule_name}(transformer, choice_pr.GetResult());\n"
        + _box_result(return_type, return_by_value)
        + f"}}\n"
    )


def generate_choice_internal_with_typed_body(rule_name, return_type, return_by_value, child_type, child_by_value):
    """
    Internal for a choice rule where all alternatives have the same transform type,
    but the rule itself returns a different type. The generated wrapper extracts the
    child value and the manual body performs the type conversion.
    """
    arg = "std::move(child)" if child_by_value else "child"
    child_extraction = (
        "\tauto &choice_result = choice_pr.GetResult();\n" + _emit_string_result_extraction("child", "choice_result")
        if child_type == "string"
        else f"\tauto child = transformer.Transform<{child_type}>(choice_pr.GetResult());\n"
    )
    return (
        f"unique_ptr<TransformResultValue> PEGTransformerFactory::Transform{rule_name}Internal(\n"
        f"    PEGTransformer &transformer, ParseResult &parse_result) {{\n"
        f"\tauto &list_pr = parse_result.Cast<ListParseResult>();\n"
        f"\tauto &choice_pr = list_pr.Child<ChoiceParseResult>(0);\n"
        + child_extraction
        + f"\tauto result = Transform{rule_name}(transformer, {arg});\n"
        + _box_result(return_type, return_by_value)
        + f"}}\n"
    )


def generate_choice_body_declaration(rule_name, return_type):
    """Declaration for the manual body that handles identifier alternatives."""
    return (
        f"\tstatic {return_type} Transform{rule_name}" f"(PEGTransformer &transformer, ParseResult &choice_result);\n"
    )


def generate_typed_choice_body_declaration(rule_name, return_type, child_type, child_by_value):
    """Declaration for a manual choice body that receives the already-transformed child value."""
    child_param = f"{child_type} child" if child_by_value else f"const {child_type} &child"
    return f"\tstatic {return_type} Transform{rule_name}(PEGTransformer &transformer, {child_param});\n"


def generate_typed_choice_body_stub(rule_name, return_type, child_type, child_by_value):
    """Stub .cpp definition for a typed choice body that must be hand-implemented."""
    child_param = f"{child_type} child" if child_by_value else f"const {child_type} &child"
    return (
        f"{return_type} PEGTransformerFactory::Transform{rule_name}(PEGTransformer &transformer, {child_param}) {{\n"
        f"\tthrow NotImplementedException(\"Transform{rule_name}\");\n"
        f"}}\n"
    )


def _format_default_initializer(cpp_type, initializer):
    """Format a rule default from grammar_types.yml as a C++ variable initializer."""
    if not initializer:
        return "{}"
    if initializer.startswith("=") or initializer.startswith("{"):
        return initializer
    return f"= {cpp_type}::{initializer}"


# ---------------------------------------------------------------------------
# Extended sequence-rule code generation
# ---------------------------------------------------------------------------


def _seq_param_decl(e):
    """Format one SeqElement as a C++ parameter declaration."""
    if e.by_value:
        return f"{e.cpp_type} {e.var_name}"
    return f"const {e.cpp_type} &{e.var_name}"


def _sequence_body_params(rule_name, rule_types, elements):
    params = ["PEGTransformer &transformer"]
    params.extend(_seq_param_decl(e) for e in elements if not e.skip)
    if rule_types[rule_name].pass_location:
        params.append("optional_idx query_location")
    return ", ".join(params)


def generate_sequence_body_decl(rule_name, return_type, rule_types, elements):
    """Declaration for the hand-written body that receives extracted typed args."""
    params = _sequence_body_params(rule_name, rule_types, elements)
    return f"\tstatic {return_type} Transform{rule_name}({params});\n"


def generate_sequence_body_stub(rule_name, return_type, rule_types, elements):
    """Stub .cpp definition for a sequence body that must be hand-implemented."""
    params = _sequence_body_params(rule_name, rule_types, elements)
    return (
        f"{return_type} PEGTransformerFactory::Transform{rule_name}({params}) {{\n"
        f"\tthrow NotImplementedException(\"Transform{rule_name}\");\n"
        f"}}\n"
    )


def generate_choice_body_stub(rule_name, return_type):
    """Stub .cpp definition for a choice body that must be hand-implemented."""
    return (
        f"{return_type} PEGTransformerFactory::Transform{rule_name}"
        f"(PEGTransformer &transformer, ParseResult &choice_result) {{\n"
        f"\tthrow NotImplementedException(\"Transform{rule_name}\");\n"
        f"}}\n"
    )


def generate_sequence_internal(rule_name, return_type, return_by_value, rule_types, elements):
    """
    Generate the Internal static class member for a sequence rule.
    Returns unique_ptr<TransformResultValue> matching transform_function_t for the static table.
    Extracts typed args from parse_result, calls the hand-written body, then boxes via TypedTransformResult.
    """
    semantic = [e for e in elements if not e.skip]
    has_semantic_elements = len(semantic) > 0

    body = []
    # Only emit the list_pr cast when there are elements to extract from it.
    # All-skip rules (e.g. CommitTransaction <- CommitOrEnd Transaction?)
    # produce no arguments and must not declare an unused list_pr variable.
    if has_semantic_elements:
        body.append("\tauto &list_pr = parse_result.Cast<ListParseResult>();")
        for elem in semantic:
            body.extend(elem.extraction_lines)

    def _param_arg(e):
        # by_value=True means move-only; transfer ownership to body via std::move.
        if e.by_value:
            return f"std::move({e.var_name})"
        return e.var_name

    args = ["transformer"] + [_param_arg(e) for e in semantic]
    if rule_types[rule_name].pass_location:
        args.append("parse_result.offset")
    body.append(f"\tauto result = Transform{rule_name}({', '.join(args)});")
    box = _box_result(return_type, return_by_value).rstrip('\n')
    body.append(box)
    return (
        f"unique_ptr<TransformResultValue> PEGTransformerFactory::Transform{rule_name}Internal(\n"
        f"    PEGTransformer &transformer, ParseResult &parse_result) {{\n" + "\n".join(body) + "\n}\n"
    )


def generate_sequence_forward_internal(rule_name, return_type, return_by_value, elements):
    semantic = [e for e in elements if not e.skip]
    assert len(semantic) == 1
    elem = semantic[0]
    body = ["\tauto &list_pr = parse_result.Cast<ListParseResult>();"]
    body.extend(elem.extraction_lines)
    result_expr = f"std::move({elem.var_name})" if elem.by_value else elem.var_name
    body.append(f"\tauto result = {result_expr};")
    box = _box_result(return_type, return_by_value).rstrip('\n')
    body.append(box)
    return (
        f"unique_ptr<TransformResultValue> PEGTransformerFactory::Transform{rule_name}Internal(\n"
        f"    PEGTransformer &transformer, ParseResult &parse_result) {{\n" + "\n".join(body) + "\n}\n"
    )


@dataclass
class GramFileResult:
    gram_stem: str
    declarations: list
    implementations: list
    registrations: list
    generated_rule_names: list  # names of rules that received an auto-generated Internal
    skipped: list  # (rule_name, reason) — nothing generated
    manual_bodies: list  # (rule_name, reason) — Internal generated, body is hand-written
    body_stubs: list  # cpp definition stubs for bodies that need hand-implementation


def collect_generated(
    gram_stem,
    rules,
    rule_types,
    excluded_rules,
    provided_rule_names,
    identifier_override_rules,
    optional_semantic_values=False,
):
    """Classify all rules; return a GramFileResult."""
    declarations = []
    implementations = []
    registrations = []
    generated_rule_names = []
    skipped = []
    manual_bodies = []
    body_stubs = []

    for rule_name, rule in rules.items():
        if rule_name in provided_rule_names:
            skipped.append((rule_name, "provided by matcher_rule_overrides"))
            continue

        if rule_name in excluded_rules:
            skipped.append((rule_name, "in excluded_rules"))
            continue

        return_type = rule.return_type
        if return_type is None:
            skipped.append((rule_name, "no return type in grammar_types.yml"))
            continue

        try:
            ast = rule_to_ast(rule)
        except Exception as e:
            skipped.append((rule_name, f"AST parse error: {e}"))
            continue

        return_by_value = _is_by_value(rule_name, rule_types)

        literals = literal_string_values(ast)
        if return_type == "string" and literals is not None and not manual_body_exists(gram_stem, rule_name):
            declarations.append(generate_internal_declaration(rule_name))
            registrations.append(generate_registration(rule_name))
            generated_rule_names.append(rule_name)
            implementations.append(generate_literal_string_internal(rule_name, literals, return_by_value))
            continue

        if is_pure_reference_choice(ast):
            transformer_alts, identifier_alts, excluded_alts, unknown_alts = classify_choice_alternatives(
                ast.alternatives, rule_types, excluded_rules, identifier_override_rules
            )
            if unknown_alts:
                skipped.append((rule_name, f"choice has unknown alternatives: {unknown_alts}"))
                continue

            declarations.append(generate_internal_declaration(rule_name))
            registrations.append(generate_registration(rule_name))
            generated_rule_names.append(rule_name)

            if not identifier_alts and not excluded_alts:
                alt_types = {rule_types[alt].cpp_type for alt in transformer_alts}
                if len(alt_types) == 1 and return_type in alt_types:
                    implementations.append(generate_choice_internal_full(rule_name, return_type, return_by_value))
                elif len(alt_types) == 1:
                    child_type = next(iter(alt_types))
                    child_by_value = any(_is_by_value(alt, rule_types) for alt in transformer_alts)
                    declarations.append(
                        generate_typed_choice_body_declaration(rule_name, return_type, child_type, child_by_value)
                    )
                    implementations.append(
                        generate_choice_internal_with_typed_body(
                            rule_name, return_type, return_by_value, child_type, child_by_value
                        )
                    )
                    manual_bodies.append((rule_name, f"choice body; wraps alternative return type: {child_type}"))
                    body_stubs.append(
                        (rule_name, generate_typed_choice_body_stub(rule_name, return_type, child_type, child_by_value))
                    )
                else:
                    declarations.append(generate_choice_body_declaration(rule_name, return_type))
                    implementations.append(generate_choice_internal_with_body(rule_name, return_type, return_by_value))
                    manual_bodies.append((rule_name, f"choice body; alternative return types: {sorted(alt_types)}"))
                    body_stubs.append((rule_name, generate_choice_body_stub(rule_name, return_type)))
            elif excluded_alts and not identifier_alts:
                alt_types = {rule_types[alt].cpp_type for alt in transformer_alts}
                if len(alt_types) == 1 and return_type in alt_types:
                    implementations.append(
                        generate_choice_internal_with_default_alternatives(
                            rule_name, return_type, return_by_value, excluded_alts
                        )
                    )
                else:
                    declarations.append(generate_choice_body_declaration(rule_name, return_type))
                    implementations.append(generate_choice_internal_with_body(rule_name, return_type, return_by_value))
                    manual_bodies.append(
                        (
                            rule_name,
                            f"choice body; syntax-only alternatives: {excluded_alts}, "
                            f"alternative return types: {sorted(alt_types)}",
                        )
                    )
                    body_stubs.append((rule_name, generate_choice_body_stub(rule_name, return_type)))
            else:
                alt_types = {rule_types[alt].cpp_type for alt in transformer_alts}
                if identifier_alts and not excluded_alts and alt_types <= {"string"}:
                    if return_type in ("string", "Identifier"):
                        # string-terminal alternatives are emitted directly as the rule's own type
                        # (Identifier-typed rules wrap keyword/string-literal alternatives in Identifier)
                        implementations.append(
                            generate_string_terminal_choice_internal(rule_name, return_type, return_by_value)
                        )
                    else:
                        child_type = "string"
                        child_by_value = False
                        declarations.append(
                            generate_typed_choice_body_declaration(rule_name, return_type, child_type, child_by_value)
                        )
                        implementations.append(
                            generate_choice_internal_with_typed_body(
                                rule_name, return_type, return_by_value, child_type, child_by_value
                            )
                        )
                        manual_bodies.append((rule_name, "choice body; wraps string terminal alternatives"))
                        body_stubs.append(
                            (
                                rule_name,
                                generate_typed_choice_body_stub(rule_name, return_type, child_type, child_by_value),
                            )
                        )
                else:
                    declarations.append(generate_choice_body_declaration(rule_name, return_type))
                    implementations.append(generate_choice_internal_with_body(rule_name, return_type, return_by_value))
                    reason_parts = []
                    if identifier_alts:
                        reason_parts.append(f"identifier alternatives: {identifier_alts}")
                    if excluded_alts:
                        reason_parts.append(f"syntax-only alternatives: {excluded_alts}")
                    manual_bodies.append((rule_name, f"choice body; {', '.join(reason_parts)}"))
                    body_stubs.append((rule_name, generate_choice_body_stub(rule_name, return_type)))
            continue

        # Normalize a single token or syntax-only choice to a one-element sequence so
        # the all-skip path generates a no-argument semantic body.
        ast_plan = plan_extraction(
            ast, rule_types, excluded_rules, identifier_override_rules, optional_semantic_values
        )
        if not isinstance(ast, (SequenceNode, ChoiceNode)) or (
            ast_plan is not None and ast_plan.kind == ExtractionKind.SKIP
        ):
            ast = SequenceNode([ast])

        if isinstance(ast, SequenceNode):
            elements = classify_sequence_elements(
                ast.children, rule_types, excluded_rules, identifier_override_rules, optional_semantic_values
            )
            if elements is not None:
                declarations.append(generate_internal_declaration(rule_name))
                registrations.append(generate_registration(rule_name))
                generated_rule_names.append(rule_name)
                semantic = [e for e in elements if not e.skip]
                if (
                    len(semantic) == 1
                    and semantic[0].cpp_type == return_type
                    and not manual_body_exists(gram_stem, rule_name)
                ):
                    implementations.append(
                        generate_sequence_forward_internal(rule_name, return_type, return_by_value, elements)
                    )
                else:
                    declarations.append(generate_sequence_body_decl(rule_name, return_type, rule_types, elements))
                    implementations.append(
                        generate_sequence_internal(rule_name, return_type, return_by_value, rule_types, elements)
                    )
                    body_stubs.append(
                        (rule_name, generate_sequence_body_stub(rule_name, return_type, rule_types, elements))
                    )
                continue
            skipped.append(
                (
                    rule_name,
                    sequence_skip_reason(
                        ast.children, rule_types, excluded_rules, identifier_override_rules, optional_semantic_values
                    ),
                )
            )
            continue

        skipped.append((rule_name, "complex rule (has operators/choices/groups)"))

    return GramFileResult(
        gram_stem=gram_stem,
        declarations=declarations,
        implementations=implementations,
        registrations=registrations,
        generated_rule_names=generated_rule_names,
        skipped=skipped,
        manual_bodies=manual_bodies,
        body_stubs=body_stubs,
    )


def print_output(result: GramFileResult):
    if result.skipped:
        print("=== SKIPPED (nothing generated) ===")
        for rule_name, reason in result.skipped:
            print(f"  {rule_name}: {reason}")
        print()

    if result.manual_bodies:
        print("=== MANUAL BODY NEEDED (Internal generated, body must be hand-written) ===")
        for rule_name, reason in result.manual_bodies:
            print(f"  {rule_name}: {reason}")
        print()

    print("=== DECLARATIONS (peg_transformer.hpp, between generated markers) ===")
    print("".join(result.declarations))

    print(f"=== IMPLEMENTATION (generated/transform_{result.gram_stem}_generated.cpp) ===")
    print("".join(result.implementations))

    print(f"=== REGISTRATION (transform_generated.cpp static table) ===")
    print("".join(result.registrations))

    if result.body_stubs:
        print(f"=== BODY STUBS (add to transform_{result.gram_stem}.cpp) ===")
        print("".join(stub for _, stub in result.body_stubs))


def generate_table_and_register(all_registrations):
    entries = "".join("\t\t" + e.lstrip() for e in all_registrations)
    return (
        "void PEGTransformerFactory::RegisterGenerated() {\n"
        + "\tstatic const TransformRule builtin_transform_rules[] = {\n"
        + entries
        + "\t};\n"
        + "\tfor (const auto &rule : builtin_transform_rules) {\n"
        + "\t\tsql_transform_functions[rule.name] = rule.transform;\n"
        + "\t}\n"
        + "}\n"
    )


def write_cpp(all_implementations, all_registrations):
    cpp_path = transformer_dir / "transform_generated.cpp"
    content = (
        GENERATED_HEADER
        + '#include "duckdb/parser/peg/transformer/peg_transformer.hpp"\n'
        + "\nnamespace duckdb {\n\n"
        + "\n".join(all_implementations)
        + "\n"
        + generate_table_and_register(all_registrations)
        + "\n} // namespace duckdb\n"
    )
    cpp_path.write_text(content)
    print(f"Wrote {cpp_path}")


_SEPARATOR = "\t//===--------------------------------------------------------------------===//\n"
_START_BLOCK = _SEPARATOR + "\t// START GENERATED RULES\n" + _SEPARATOR
_END_BLOCK = _SEPARATOR + "\t// END GENERATED RULES\n" + _SEPARATOR
_MATCHER_START_BLOCK = _SEPARATOR + "\t// START GENERATED RULE OVERRIDES\n" + _SEPARATOR
_MATCHER_END_BLOCK = _SEPARATOR + "\t// END GENERATED RULE OVERRIDES\n" + _SEPARATOR


def _matcher_override_expr(rule_name, override):
    matcher = override.get("matcher")
    suggestion = override.get("suggestion")
    if matcher == "identifier":
        if suggestion:
            return f"allocator.Allocate(make_uniq<IdentifierMatcher>(SuggestionState::{suggestion}))"
    if matcher == "reserved_identifier":
        if suggestion:
            return f"allocator.Allocate(make_uniq<ReservedIdentifierMatcher>(SuggestionState::{suggestion}))"
    if matcher == "number_literal":
        return "allocator.Allocate(make_uniq<NumberLiteralMatcher>())"
    if matcher == "string_literal":
        return "allocator.Allocate(make_uniq<StringLiteralMatcher>())"
    if matcher == "operator":
        return "allocator.Allocate(make_uniq<OperatorMatcher>())"
    raise RuntimeError(f"Unsupported matcher_rule_overrides entry for {rule_name}: {override}")


def write_matcher_rule_overrides(matcher_overrides):
    content = matcher_cpp_path.read_text()
    start_idx = content.find(_MATCHER_START_BLOCK)
    if start_idx == -1:
        raise RuntimeError(f"Could not find START GENERATED RULE OVERRIDES marker in {matcher_cpp_path}")
    end_idx = content.find(_MATCHER_END_BLOCK, start_idx + len(_MATCHER_START_BLOCK))
    if end_idx == -1:
        raise RuntimeError(f"Could not find END GENERATED RULE OVERRIDES marker in {matcher_cpp_path}")

    lines = []
    for rule_name, override in matcher_overrides.items():
        if not isinstance(override, dict):
            raise RuntimeError(f"matcher_rule_overrides entry for {rule_name} must be a mapping")
        expr = _matcher_override_expr(rule_name, override)
        line = f'\tAddRuleOverride("{rule_name}", {expr});\n'
        if len(line.rstrip()) <= 120:
            lines.append(line)
        else:
            lines.append(f'\tAddRuleOverride("{rule_name}",\n')
            lines.append(f'\t                {expr});\n')

    block_end = end_idx + len(_MATCHER_END_BLOCK)
    generated_block = _MATCHER_START_BLOCK + "".join(lines) + _MATCHER_END_BLOCK
    new_content = content[:start_idx] + generated_block + content[block_end:]
    matcher_cpp_path.write_text(new_content)
    print(f"Updated {matcher_cpp_path}")


def write_hpp(all_declarations):
    hpp_path = include_peg_dir / "peg_transformer.hpp"
    content = hpp_path.read_text()

    start_idx = content.find(_START_BLOCK)
    if start_idx == -1:
        raise RuntimeError(f"Could not find START GENERATED RULES marker in {hpp_path}")
    end_idx = content.find(_END_BLOCK, start_idx + len(_START_BLOCK))
    if end_idx == -1:
        raise RuntimeError(f"Could not find END GENERATED RULES marker in {hpp_path}")

    block_end = end_idx + len(_END_BLOCK)
    generated_block = _START_BLOCK + "".join(all_declarations) + _END_BLOCK
    new_content = content[:start_idx] + generated_block + content[block_end:]
    hpp_path.write_text(new_content)
    print(f"Updated {hpp_path}")


def _extract_func_signature(text, func_name):
    """Extract 'ReturnType PEGTransformerFactory::func_name(params)' from C++ source text."""
    m = re.search(rf'\bPEGTransformerFactory::{re.escape(func_name)}\s*\(', text)
    if not m:
        return None
    line_start = text.rfind('\n', 0, m.start()) + 1
    paren_start = text.index('(', m.start())
    depth = 0
    for i, char in enumerate(text[paren_start:]):
        if char == '(':
            depth += 1
        elif char == ')':
            depth -= 1
            if depth == 0:
                return text[line_start : paren_start + i + 1]
    return None


def _norm_ws(s):
    s = re.sub(r'\s+', ' ', s).strip()
    s = re.sub(r'\(\s+', '(', s)
    s = re.sub(r'\s+\)', ')', s)
    return s


def _check_implementations(gram_stem, body_stubs):
    """Check which body stubs are implemented in any transform_*.cpp file.

    Compares from PEGTransformerFactory:: onwards (normalized whitespace) so that return types
    split across lines and multi-line param lists are handled correctly.

    Returns (implemented, mismatched):
      implemented: set of rule_names whose signature exactly matches the stub
      mismatched:  set of rule_names that exist but only with a different signature
    """
    preferred_path = transformer_dir / f"transform_{gram_stem}.cpp"
    paths = [preferred_path] if preferred_path.exists() else []
    paths.extend(path for path in transformer_dir.glob("transform_*.cpp") if path != preferred_path)
    prefix = 'PEGTransformerFactory::'
    implemented = set()
    mismatched = set()
    for rule_name, stub_cpp in body_stubs:
        first_line = stub_cpp.split('\n')[0]
        expected = _norm_ws(first_line.rstrip('{').rstrip())
        expected_norm = expected[expected.find(prefix) :] if prefix in expected else expected
        found_mismatch = False
        for path in paths:
            actual = _extract_func_signature(path.read_text(), f'Transform{rule_name}')
            if actual is None:
                continue
            actual = _norm_ws(actual)
            actual_norm = actual[actual.find(prefix) :] if prefix in actual else actual
            if expected_norm == actual_norm:
                implemented.add(rule_name)
                found_mismatch = False
                break
            found_mismatch = True
        if found_mismatch and rule_name not in implemented:
            mismatched.add(rule_name)
    return implemented, mismatched


def _find_stale_manual_internals(gram_stem, generated_rule_names):
    """Return rules whose Internal is now auto-generated but still exists in transform_{gram_stem}.cpp."""
    cpp_path = transformer_dir / f"transform_{gram_stem}.cpp"
    if not cpp_path.exists():
        return []
    text = cpp_path.read_text()
    return [
        name
        for name in sorted(generated_rule_names)
        if re.search(rf'\bPEGTransformerFactory::Transform{re.escape(name)}Internal\s*\(', text)
    ]


def print_manual_steps(all_results):
    print("\nRemaining manual steps:")

    step = 1

    all_skipped = [
        (r.gram_stem, rule_name, reason)
        for r in all_results
        for rule_name, reason in r.skipped
        if not reason.startswith("provided by ")
    ]
    if all_skipped:
        print(f"\n  {step}. Skipped rules (not auto-generated):")
        current_stem = None
        for gram_stem, rule_name, reason in all_skipped:
            if gram_stem != current_stem:
                print(f"\n       {gram_stem}.gram:")
                current_stem = gram_stem
            print(f"         {rule_name}: {reason}")
        step += 1

    stale_by_stem = {}
    for r in all_results:
        if r.generated_rule_names:
            stale = _find_stale_manual_internals(r.gram_stem, r.generated_rule_names)
            if stale:
                stale_by_stem[r.gram_stem] = stale
    if stale_by_stem:
        print(f"\n  {step}. Stale manual Internal wrappers (now auto-generated; remove from transform_*.cpp):")
        for gram_stem, rule_names in sorted(stale_by_stem.items()):
            print(f"\n       transform_{gram_stem}.cpp:")
            for name in rule_names:
                print(f"         Transform{name}Internal")
        step += 1

    has_any_stubs = any(r.body_stubs for r in all_results)
    if has_any_stubs:
        pending_stubs = []
        sig_mismatches = []
        for r in all_results:
            if not r.body_stubs:
                continue
            implemented, mismatched = _check_implementations(r.gram_stem, r.body_stubs)
            for rule_name, stub in r.body_stubs:
                if rule_name in implemented:
                    pass
                elif rule_name in mismatched:
                    sig_mismatches.append((r.gram_stem, rule_name, stub.split('\n')[0].rstrip('{').rstrip()))
                else:
                    pending_stubs.append((r.gram_stem, stub))

        if sig_mismatches:
            print(f"\n  {step}. Signature mismatches (function exists but params don't match generated declaration):")
            current_stem = None
            for gram_stem, rule_name, expected_sig in sig_mismatches:
                if gram_stem != current_stem:
                    print(f"\n       transform_{gram_stem}.cpp:")
                    current_stem = gram_stem
                print(f"         Transform{rule_name} -- update to: {expected_sig}")
            step += 1

        if pending_stubs:
            print(f"\n  {step}. Body stubs to implement (copy into respective transform_*.cpp files):")
            current_stem = None
            for gram_stem, stub in pending_stubs:
                if gram_stem != current_stem:
                    print(f"\n       // transform_{gram_stem}.cpp")
                    current_stem = gram_stem
                for line in stub.splitlines():
                    print(f"       {line}")
                print()
            step += 1

        if not sig_mismatches and not pending_stubs:
            print(f"\n  {step}. All user-implemented body stubs already found in transform_*.cpp files.")
            step += 1


def process_gram_file(gram_filename, rule_types, excluded_rules, provided_rule_names, identifier_override_rules):
    """Parse a .gram file and classify all its rules into a GramFileResult."""
    gram_stem = gram_filename.removesuffix('.gram')
    gram_path = statements_dir / gram_filename
    try:
        rules = parse_peg_grammar(gram_path.read_text())
    except Exception as e:
        raise Exception(f"{gram_filename}: {e}") from None

    for rule_name, info in rule_types.items():
        if rule_name in rules:
            rules[rule_name].return_type = info.cpp_type

    return collect_generated(
        gram_stem,
        rules,
        rule_types,
        excluded_rules,
        provided_rule_names,
        identifier_override_rules,
        optional_semantic_values=True,
    )


def main():
    arg_parser = argparse.ArgumentParser(description="Generate Internal transformer wrappers from grammar rules.")
    arg_parser.add_argument("--write", action="store_true", help="Write generated files to disk.")
    args = arg_parser.parse_args()

    gram_files_to_gen = sorted(path.name for path in statements_dir.glob('*.gram'))
    grammar_types_file = type_dir / 'grammar_types.yml'
    matcher_overrides = load_matcher_rule_overrides(grammar_types_file)
    matcher_rule_names = set(matcher_overrides.keys())
    identifier_override_rules = load_identifier_override_rules(grammar_types_file)
    rule_types, excluded_rules = load_grammar_types(grammar_types_file)
    results = [
        process_gram_file(f, rule_types, excluded_rules, matcher_rule_names, identifier_override_rules)
        for f in gram_files_to_gen
    ]

    if args.write:
        all_declarations = [d for r in results for d in r.declarations]
        write_hpp(all_declarations)
        all_implementations = [impl for r in results for impl in r.implementations]
        all_registrations = [reg for r in results for reg in r.registrations]
        write_cpp(all_implementations, all_registrations)
        write_matcher_rule_overrides(matcher_overrides)
        print_manual_steps(results)
    else:
        for r in results:
            print(f"\n{'=' * 60}")
            print(f"  {r.gram_stem}.gram")
            print(f"{'=' * 60}")
            print_output(r)


if __name__ == "__main__":
    main()
